# -*- coding: utf-8 -*-
"""python_etl_snippet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t4yBsb0TCrUrUiyZyAcAcmrHQ_p8zale
"""

"""
📦 Indonesia Earthquake ETL Snippet
Author: Bramantya Wibisono (brbelajardata)
Description: Extract data from USGS API → Transform with pandas → Load to BigQuery
"""

import pandas as pd
import requests
from google.cloud import bigquery

# 1️⃣ Extract: Ambil data dari API USGS
url = "https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&limit=100"
response = requests.get(url)
data_json = response.json()

# 2️⃣ Transform: Normalisasi JSON ke DataFrame
df = pd.json_normalize(data_json["features"])

# 3️⃣ Tambahkan metadata waktu ingestion
df["ingested_at"] = pd.Timestamp.now(tz="Asia/Jakarta")

# 4️⃣ Load: Kirim ke BigQuery (contoh table)
df.to_gbq(
    destination_table="brbelajardata.data_gempa_indonesia.raw_data",
    project_id="brbelajardata",
    if_exists="replace"
)

print("✅ ETL berhasil dijalankan: Data terbaru telah dimuat ke BigQuery.")