# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1guU2Bwfxr-kShVxiXOJYS100W82pLTvD
"""

import pandas as pd
import streamlit as st

# Page Configuration
st.set_page_config(
    page_title="E-Commerce Dashboard",
    layout="wide"
)

st.title("📊 E-Commerce Performance Dashboard")
st.caption("Ringkasan performa bisnis berdasarkan data transaksi e-commerce by brwibisono")

# Load Data
DATA_PATH = "dashboard/main_data.csv"
df = pd.read_csv(DATA_PATH)

df["order_month"] = pd.to_datetime(df["order_month"])

# Sidebar Filter
st.sidebar.header("Filter Data")

min_date = df["order_month"].min().date()
max_date = df["order_month"].max().date()

date_range = st.sidebar.date_input(
    "Pilih rentang tanggal:",
    value=(min_date, max_date),
    min_value=min_date,
    max_value=max_date
)

start_date, end_date = pd.to_datetime(date_range[0]), pd.to_datetime(date_range[1])
df_filtered = df[
    (df["order_month"] >= start_date) &
    (df["order_month"] <= end_date)
]

# KPI Section
col1, col2, col3, col4 = st.columns(4)

col1.metric("Total Orders", f"{int(df_filtered['orders'].sum()):,}")
col2.metric("Total Revenue", f"{df_filtered['revenue'].sum():,.2f}")
col3.metric("Avg Orders / Month", f"{df_filtered['orders'].mean():,.1f}")
col4.metric("Avg Revenue / Month", f"{df_filtered['revenue'].mean():,.2f}")

st.divider()

# Trend Chart
st.subheader("📈 Tren Bulanan Orders dan Revenue")

st.line_chart(
    df_filtered.set_index("order_month")[["orders", "revenue"]]
)

# Raw Data
with st.expander("Lihat data dashboard"):
    st.dataframe(df_filtered)