# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKd-wy_m_pfqF27gFoNplLwO4Yfm_RQk
"""

import os
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Page Configuration
st.set_page_config(
    page_title="E-Commerce Revenue Dashboard (2017–2018)",
    layout="wide"
)

st.title("E-Commerce Revenue Dashboard (2017–2018)")
st.write(
    "Dashboard interaktif untuk menganalisis kontribusi kategori produk "
    "dan tren pendapatan bisnis berdasarkan rentang tanggal."
)

# Load Data
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

main_data = pd.read_csv(os.path.join(BASE_DIR, "main_data.csv"))
product_revenue = pd.read_csv(os.path.join(BASE_DIR, "product_revenue.csv"))

main_data["order_date"] = pd.to_datetime(main_data["order_date"])
product_revenue["order_date"] = pd.to_datetime(product_revenue["order_date"])

# Sidebar Filter (Date-based)
st.sidebar.header("Filter Tanggal")

min_date = main_data["order_date"].min().date()
max_date = main_data["order_date"].max().date()

start_date, end_date = st.sidebar.date_input(
    "Pilih Rentang Tanggal",
    value=(min_date, max_date),
    min_value=min_date,
    max_value=max_date
)

# Apply Filter
filtered_main_data = main_data[
    (main_data["order_date"].dt.date >= start_date) &
    (main_data["order_date"].dt.date <= end_date)
]

filtered_product_revenue = product_revenue[
    (product_revenue["order_date"].dt.date >= start_date) &
    (product_revenue["order_date"].dt.date <= end_date)
]

# Business Question 1
st.subheader(
    "Kategori Produk dengan Kontribusi Pendapatan Tertinggi"
)

top10_product = (
    filtered_product_revenue
    .groupby("product_category_name", as_index=False)
    .agg(total_revenue=("total_revenue", "sum"))
    .sort_values("total_revenue", ascending=False)
    .head(10)
)

fig1, ax1 = plt.subplots(figsize=(8, 5))
ax1.barh(
    top10_product["product_category_name"][::-1],
    top10_product["total_revenue"][::-1]
)
ax1.set_xlabel("Total Revenue")
ax1.set_ylabel("Product Category")
ax1.set_title("Top Product Categories by Revenue")

st.pyplot(fig1)

# Business Question 2
st.subheader(
    "Tren Pendapatan Bisnis Berdasarkan Waktu"
)

daily_revenue = (
    filtered_main_data
    .groupby("order_date", as_index=False)
    .agg(total_revenue=("total_revenue", "sum"))
)

fig2, ax2 = plt.subplots(figsize=(10, 4))
ax2.plot(
    daily_revenue["order_date"],
    daily_revenue["total_revenue"]
)
ax2.set_xlabel("Order Date")
ax2.set_ylabel("Total Revenue")
ax2.set_title("Daily Revenue Trend")

st.pyplot(fig2)

# Conclusion
st.subheader("Kesimpulan")

st.markdown(
    """
    - Kontribusi pendapatan bisnis didominasi oleh beberapa kategori produk utama,
      dan komposisi ini dapat berubah tergantung rentang tanggal yang dianalisis.
    - Tren pendapatan menunjukkan fluktuasi dari hari ke hari, sehingga analisis
      berbasis tanggal membantu memahami dinamika performa bisnis secara lebih detail.
    """
)

st.markdown(
    """
    **Bramantya Wibisono**  
    Submission Dicoding – Proyek Analisis Data  
    **br.wibisono@gmail.com**
    """
)
