# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKd-wy_m_pfqF27gFoNplLwO4Yfm_RQk
"""

import os
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Page Configuration
st.set_page_config(
    page_title="E-Commerce Revenue Dashboard (2017–2018)",
    layout="wide"
)

st.title("E-Commerce Revenue Dashboard (2017–2018)")
st.write(
    "Visualisasi untuk menjawab pertanyaan bisnis terkait kontribusi kategori produk dan tren pendapatan bulanan."
)
# Load Data
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

main_data = pd.read_csv(os.path.join(BASE_DIR, "main_data.csv"))
product_revenue = pd.read_csv(os.path.join(BASE_DIR, "product_revenue.csv"))

# Sidebar Filter (Interactivity)
st.sidebar.header("Filter Data")

available_months = sorted(main_data["order_month"].unique())
selected_month = st.sidebar.selectbox(
    "Pilih Bulan",
    options=["Semua"] + available_months
)

if selected_month != "Semua":
    filtered_main_data = main_data[
        main_data["order_month"] == selected_month
    ]
else:
    filtered_main_data = main_data.copy()

# Business Question 1
st.subheader(
    "Kategori Produk Kontributor Utama Pendapatan (2017–2018)"
)

top10_product = product_revenue.head(10)

fig1, ax1 = plt.subplots(figsize=(8, 5))
ax1.barh(
    top10_product["product_category_name"][::-1],
    top10_product["total_revenue"][::-1]
)
ax1.set_xlabel("Total Revenue")
ax1.set_ylabel("Product Category")
ax1.set_title(
    "Top Product Categories by Revenue Contribution (2017–2018)"
)

st.pyplot(fig1)

st.markdown(
    """
    **Insight:**
    - Pendapatan bisnis terkonsentrasi pada beberapa kategori produk utama
      yang menjadi kontributor terbesar selama periode analisis.
    """
)

# Business Question 2
st.subheader(
    "Tren Pendapatan Bisnis Bulanan (2017–2018)"
)

fig2, ax2 = plt.subplots(figsize=(10, 4))
ax2.plot(
    filtered_main_data["order_month"],
    filtered_main_data["total_revenue"],
    marker="o"
)
ax2.set_xlabel("Order Month")
ax2.set_ylabel("Total Revenue")
ax2.set_title("Monthly Revenue Trend (2017–2018)")
plt.xticks(rotation=45)

st.pyplot(fig2)

st.markdown(
    """
    **Insight:**
    - Pendapatan bisnis menunjukkan tren pertumbuhan dari bulan ke bulan
      selama 2017–2018, meskipun terdapat fluktuasi pada beberapa periode.
    """
)

# Conclusion
st.subheader("Kesimpulan")

st.markdown(
    """
    - Kategori produk tertentu menjadi pendorong utama pendapatan bisnis,
      sehingga fokus pada kategori unggulan berpotensi memberikan dampak
      terbesar terhadap kinerja pendapatan.
    - Tren pendapatan bulanan menunjukkan pertumbuhan yang positif, yang
      menegaskan pentingnya pemantauan kinerja bisnis secara berkala.
    """
)

st.markdown(
    """
    **Bramantya Wibisono**
    | Submission Dicoding - Proyek Analisis Data
    | **br.wibisono@gmail.com**
    """
)
