# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MsiOY4uLdxFT7bq3_sX1QW-XxusPpIa6
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import plotly.graph_objects as go
import plotly.express as px

# KONFIGURASI HALAMAN

st.set_page_config(
    page_title="🎓 Prediksi Dropout Mahasiswa",
    layout="wide"
)

st.title("🎓 Prediksi Dropout Mahasiswa")
st.markdown("Dashboard interaktif untuk memprediksi risiko mahasiswa dropout by Bramantya Wibisono")


# LOAD MODEL

model = joblib.load("etl_python_bigquery/submission/model/student_dropout_model.pkl")
feature_columns = joblib.load("etl_python_bigquery/submission/model/model_features.pkl")

# DEBUG (optional tapi bagus untuk reviewer)
with st.expander("🔍 Model Info"):
    st.write("Features used:", feature_columns)


# TABS

tab1, tab2 = st.tabs(
    ["🔍 Prediksi Individu", "📊 Prediksi Batch"]
)


# TAB 1 — PREDIKSI INDIVIDU

with tab1:

    st.subheader("📝 Input Profil Mahasiswa")

    col1, col2 = st.columns(2)

    input_data = {}

    with col1:
        input_data["Admission_grade"] = st.number_input("Nilai Masuk", 0.0, 200.0, 120.0)

        input_data["Age_at_enrollment"] = st.number_input("Usia Saat Pendaftaran", 15, 60, 20)

        input_data["Tuition_fees_up_to_date"] = st.selectbox(
            "Status Pembayaran UKT",
            [1, 0],
            format_func=lambda x: "Lunas" if x == 1 else "Belum Lunas"
        )

        input_data["Scholarship_holder"] = st.selectbox(
            "Penerima Beasiswa",
            [1, 0],
            format_func=lambda x: "Ya" if x == 1 else "Tidak"
        )

    with col2:
        input_data["Debtor"] = st.selectbox(
            "Status Hutang",
            [1, 0],
            format_func=lambda x: "Punya Hutang" if x == 1 else "Tidak Punya Hutang"
        )

        input_data["Curricular_units_1st_sem_approved"] = st.number_input(
            "Jumlah Matkul Lulus Semester 1", 0, 20, 5
        )

        input_data["Curricular_units_1st_sem_grade"] = st.number_input(
            "Nilai Semester 1", 0.0, 20.0, 12.0
        )

        input_data["Curricular_units_2nd_sem_grade"] = st.number_input(
            "Nilai Semester 2", 0.0, 20.0, 12.0
        )


    # BUILD INPUT DATAFRAME

    input_df = pd.DataFrame(
        [np.zeros(len(feature_columns))],
        columns=feature_columns
    )

    for col, value in input_data.items():
        if col in input_df.columns:
            input_df[col] = value


    # PREDIKSI

    if st.button("🚀 Prediksi Risiko Dropout", use_container_width=True):

        # VALIDASI FITUR
        missing_cols = [col for col in feature_columns if col not in input_df.columns]

        if len(missing_cols) > 0:
            st.error(f"Fitur tidak lengkap: {missing_cols}")
            st.stop()

        # PASTIKAN URUTAN KOLOM SESUAI MODEL
        input_df = input_df[feature_columns]

        probability = model.predict_proba(input_df)[0][1]
        probability_pct = probability * 100

        st.divider()
        st.subheader("📊 Hasil Analisis Risiko")

        col_left, col_right = st.columns([1, 1])

        # GAUGE
        with col_left:
            fig_gauge = go.Figure(go.Indicator(
                mode="gauge+number",
                value=probability_pct,
                number={"suffix": "%"},
                title={"text": "Probabilitas Dropout"},
                gauge={
                    "axis": {"range": [0, 100]},
                    "bar": {"color": "black"},
                    "steps": [
                        {"range": [0, 30], "color": "#d4edda"},
                        {"range": [30, 60], "color": "#fff3cd"},
                        {"range": [60, 100], "color": "#f8d7da"}
                    ]
                }
            ))

            st.plotly_chart(fig_gauge, use_container_width=True)

        # KANAN — STATUS + BAR CHART
        with col_right:

            st.metric(
                "Probabilitas Prediksi",
                f"{probability_pct:.2f}%"
            )

            if probability >= 0.7:
                st.error("🚨 Risiko Sangat Tinggi")
            elif probability >= 0.5:
                st.warning("⚠️ Risiko Tinggi")
            elif probability >= 0.3:
                st.info("🔍 Risiko Sedang")
            else:
                st.success("✅ Risiko Rendah / Aman")

            # Faktor risiko visual
            risk_factors = {
                "Pembayaran": 100 if input_data["Tuition_fees_up_to_date"] == 0 else 20,
                "Hutang": 100 if input_data["Debtor"] == 1 else 20,
                "Nilai Sem 1": max(0, 100 - input_data["Curricular_units_1st_sem_grade"] * 5),
                "Nilai Sem 2": max(0, 100 - input_data["Curricular_units_2nd_sem_grade"] * 5)
            }

            risk_df = pd.DataFrame({
                "Faktor": list(risk_factors.keys()),
                "Skor Risiko": list(risk_factors.values())
            })

            fig_bar = px.bar(
                risk_df,
                x="Faktor",
                y="Skor Risiko",
                title="Faktor Risiko Utama"
            )

            st.plotly_chart(fig_bar, use_container_width=True)


        # REKOMENDASI

        st.markdown("### 🧠 Rekomendasi Tindakan")

        if probability >= 0.5:
            st.warning("""
            - mentoring akademik
            - follow-up pembayaran
            - evaluasi performa
            """)
        else:
            st.success("Monitoring berkala disarankan")


# TAB 2 — BATCH

with tab2:

    st.subheader("📂 Upload CSV untuk Prediksi Batch")

    uploaded_file = st.file_uploader("Upload file CSV", type=["csv"])

    if uploaded_file is not None:
        batch_df = pd.read_csv(uploaded_file, sep=";")

        st.subheader("📄 Data Asli")
        st.dataframe(batch_df.head())

        # VALIDASI KOLOM
        missing_cols = [col for col in feature_columns if col not in batch_df.columns]

        if len(missing_cols) > 0:
            st.error(f"Kolom tidak lengkap: {missing_cols}")
            st.stop()

        batch_input = batch_df[feature_columns]

        batch_prob = model.predict_proba(batch_input)[:, 1]

        batch_df["Probabilitas_Dropout"] = batch_prob
        batch_df["Prediksi"] = np.where(
            batch_prob >= 0.5,
            "Risiko Tinggi",
            "Risiko Rendah"
        )

        st.subheader("📊 Hasil Prediksi")
        st.dataframe(batch_df.head())

        st.download_button(
            "⬇️ Download Hasil",
            batch_df.to_csv(index=False).encode("utf-8"),
            "hasil_prediksi.csv",
            "text/csv"
        )
